### Test 1: Valid Chirp (Should return 200 OK with valid: true)
POST http://localhost:80/api/validate_chirp
Content-Type: application/json

{
    "body": "Hello world! This is a valid chirp under 140 characters."
}

###

### Test 2: Invalid Chirp (Should return 400 Bad Request with error)
POST http://localhost:80/api/validate_chirp
Content-Type: application/json

{
    "body": "This chirp is intentionally designed to be way too long. It will easily surpass the one hundred and forty character limit set by the strict rules of the Chirpy platform backend assignment."
}

###

### Test 3: Bad JSON Input (Should return 400 Bad Request)
POST http://localhost:80/api/validate_chirp
Content-Type: application/json

{
  "body": "This is a kerfuffle opinion I need to share with the world"
}

### Variables
@baseUrl = http://localhost:8080

---

### Create a New User
# Click "Send Request" below this line to test your sqlc insert
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "email": "birdie@example.com"
}

---

### Reset the Database (Dev Only)
# Click "Send Request" to test your sqlc delete and hits wipe
POST {{baseUrl}}/admin/reset
Content-Type: application/json